version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend/shipone-backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./apps/backend/shipone-backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./apps/frontend/shipone-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/frontend/shipone-frontend:/app
    working_dir: /app
    depends_on:
      - backend

